# Generated by Django 5.0.3 on 2024-04-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230301_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isDoctor',
            field=models.BooleanField(default=False),
        ),
    ]
