# Generated by Django 5.0.3 on 2024-04-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_isdoctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
