# Generated by Django 5.0.3 on 2024-04-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
