# Generated by Django 5.0.3 on 2024-04-16 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='pdf_file',
            new_name='file',
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
