# Generated by Django 5.0.3 on 2024-04-20 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_pdf_file_report_file_report_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
