# Generated by Django 5.0.3 on 2024-04-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_user_gender_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='isModified',
            field=models.BooleanField(default=False),
        ),
    ]
